const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";
const REFETCH_NOTIFICATIONS = "REFETCH_NOTIFICATIONS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";
const REFETCH_PROFILE = "REFETCH_PROFILE";

const UPDATE_FRIENDSHIP_STATUS = "UPDATE_FRIENDSHIP_STATUS";

const REFETCH_FRIEND_LIST = "REFETCH_FRIEND_LIST";

module.exports = {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  REFETCH_NOTIFICATIONS,
  REFETCH_PROFILE,
  UPDATE_FRIENDSHIP_STATUS,
  REFETCH_FRIEND_LIST,
};
